### ISSUE TITLE
Latest release is v5, not v6

### ISSUE THREAD

**Issue by davidsoergel** [my-flow/paypalimporter#10]
It looks like v6 was tagged, but no mxt was built and it's not available via http://infinitekind.com/extensions.  I know I can build it myself, but it would be nice to be able to autoinstall it to pick up the fix for issue #9 .  Thanks!

**Comment by my-flow** [comment]
@davidsoergel, I have attached an _unsigned_ MXT file to [pre-release v6](https://github.com/my-flow/paypalimporter/releases/tag/v6), which can be downloaded and installed in Moneydance via the **“Add From File…”** option. Since this release is (still?) unsigned, installation will show a warning message saying that the signature of the extension is “invalid or missing”.

As an third-party developer I cannot sign the new version of the PayPal importer extension myself and I cannot publish the new version to http://infinitekind.com/extensions for auto-update either.

@sreilly Any news on when you can sign and publish v6?

**Comment by davidsoergel** [comment]
Confirmed this works.  Thanks so much!
