### ISSUE TITLE
Imports Authorisations and Temporary holds and removal thereof - but not all

### ISSUE THREAD

**Issue by Jim78324279** [my-flow/paypalimporter#18]
When I download the transactions into my Paypal account in Moneydance, the download includes transactions such as 

- Authorization
- Removed <xxx> Temporary Hold

BUT there always seem to be one or more that show a removal but not the associated authorization, or an authorization but no removal. I either have to delete them or put in a balancing item.  If I delete them, they are just downloaded again.

Can both of those types just be filtered out so that they are not downloaded at all please?  They don't add to anything.

**Comment by my-flow** [comment]
@Jim78324279, thanks for suggesting that! I will filter out authorizations as suggested since this is a use cases I can replicate.

However, temporary holds are a different beast and I'm having trouble simulating temporary holds using a [PayPal sandbox account](https://developer.paypal.com/tools/sandbox/accounts/). If those are still a concern, please open a separate issue, so that we can discuss options how to replicate them.
