### ISSUE TITLE
API username and signature not being remembered

### ISSUE THREAD

**Issue by my-flow** [my-flow/paypalimporter#9]
Since Moneydance 2015.7 (build1358), the download dialog box no longer remembers the API username or signature from request to request. In other words, the user needs to re-enter those every time s/he downloads from PayPal. The API password is remembered.

**Comment by HeyShay** [comment]
I am having an issue where the API Username and Signature is saved, but the password is blank. I haven't used this software in a while and have no clue where I recover this information! came here to see if this was a known issue and how to repair it.

**Comment by my-flow** [comment]
@HeyShay, the API username and the signature should always be stored. However, to store the API password as well, you must [encrypt your data file](http://help.infinitekind.com/kb/program-basics/how-do-i-encrypt-my-data-file).

You can [login on PayPal](https://www.paypal.com/us/cgi-bin/webscr?cmd=_login-api-run) to figure out all your credentials including the API password.

**Comment by my-flow** [comment]
@sreilly I'm well aware that I'm using undocumented (internal) API's here, so this is just a quick heads up:

Starting with Moneydance 2015.7 (build 1358) the `isSameAs` method compares `OnlineService`s by checking for `null` values:

```java
public boolean isSameAs(OnlineService otherSvc) {
  …
  String otherTIKID = otherSvc.getTIKServiceID();
  String myTIKID = getTIKServiceID();
  if (otherTIKID != null && myTIKID != null) {
    return otherTIKID.equals(myTIKID);
  }
  …
}
```

But it sets the default of the respective attribute to the empty string instead of `null` (this is a recent change):

```java
public String getTIKServiceID() {
  return getParameter("tik_fi_id", info.getString("id", ""));
}
```

As a result the PayPal online service that the PayPal importer extension creates cannot be found anymore when iterating over all services and the user cannot see the saved credentials.

I will fix this issue on my side by using a custom subclass of  `OnlineService` that overwrites the `isSameAs` method.

**Comment by sreilly** [comment]
Hi Florian,

Yes, for a while now we've been assigning unique identifiers to all OFX services which are used to check for updates and generally to uniquely identify online services since we've come across instances in which the service-specific (OFX) bank identifiers were not always unique.  I will set aside "mdext:paypalimporter" as a TIK service ID that you can set in your OnlineService instance by calling .setParameter(OnlineService.ITEM_KEY_FI_TIK_ID, "mdext:paypalimporter").

To be honest, I'd recommend not using your own OnlineService object at all.  I certainly wouldn't use a subclass of it, because that subclass wouldn't be reloaded when the data file was opened again on that or another computer.  What functions of the OnlineService instances are you using?

Even if you do want to keep using the OnlineService object you can cache the authentication details a bit more directly by calling the .getLocalStorage() on the AccountBook for the data file and then using the cacheAuthentication/getCachedAuthentication methods in there (http://infinitekind.com/dev/apidoc/com/infinitekind/moneydance/model/LocalStorage.html).  Please make sure to use a sufficiently unique prefix for any keys that you use to store in there.  That authentication cache is the same mechanism that is used by the built-in online banking system, so it will store passwords in memory while Moneydance is running but is cleared whenever Moneydance is restarted.

Thanks!
Sean

**Comment by my-flow** [comment]
Hi Sean,

Thank you for your extensive response.

> I will set aside "mdext:paypalimporter" as a TIK service ID that you can set in your OnlineService instance by calling `.setParameter(OnlineService.ITEM_KEY_FI_TIK_ID, "mdext:paypalimporter")`.

Yes, that makes sense and it solves the problem with comparing different `OnlineService`s. I don't have to implement my own `isSameAs` method then!

Just some use cases on how the extension is supposed to work:

1. Store credentials of **multiple** PayPal accounts: User selects an existing bank account from sidebar and opens PayPal Importer extension. Credentials of the PayPal account that is assigned to the selected bank account are already being prefilled in the extension's download form. User selects *another* bank account from sidebar and opens PayPal Importer extension. Credentials of the *other* PayPal account are being prefilled in the extension's download form.

2. Store PayPal **password** only if encryption is enabled: PayPal password is stored in memory while Moneydance is running, but is cleared whenever Moneydance is restarted. Only if Moneydance’s encryption password is entered and the option *Store Online Passwords in File* is active, PayPal password is stored permanently.

3. Store PayPal user name and PayPal signature **permanently**: Even if the user restarts the Moneydance app, entered user name and signature are still saved, regardless whether Moneydance's encryption feature is enabled or not.


- Requirement 1 is implemented with an account-specific [realm](https://github.com/my-flow/paypalimporter/blob/v6/core/src/main/java/com/moneydance/modules/features/paypalimporter/integration/PayPalOnlineService.java#L151).
- [Requirement 2 is implemented](https://github.com/my-flow/paypalimporter/blob/v6/core/src/main/java/com/moneydance/modules/features/paypalimporter/integration/PayPalOnlineService.java#L95) using the `cacheAuthentication`/`getCachedAuthentication` methods in [LocalStorage](http://infinitekind.com/dev/apidoc/com/infinitekind/moneydance/model/LocalStorage.html) as you suggested.
- [Requirement 3 is implemented](https://github.com/my-flow/paypalimporter/blob/v6/core/src/main/java/com/moneydance/modules/features/paypalimporter/integration/PayPalOnlineService.java#L72) using `setUserId`/`getUserId` and `addParameters`/`getParameter` to make sure the credentials survive restart.

Is that the correct way to go?

Thanks,
Florian
